apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ec2-terraform-module
  description: EC2 instance managed by Terraform
  tags:
    - terraform
    - ec2
spec:
  type: resource
  lifecycle: production
  owner: team-name
  dependsOn:
    - resource:aws:ec2
  providesApis:
    - api:my-ec2-service
  terraform:
    module:
      path: terraform-aws-modules/ec2-instance/aws
      version: v3.0.0
